#![allow(clippy::many_single_char_names)]

use chia_vdf_verify::bqfc::BQFC_FORM_SIZE;
use chia_vdf_verify::discriminant::create_discriminant;
use chia_vdf_verify::form::Form;
use chia_vdf_verify::integer::{fdiv_r, from_bytes_be, num_bits};
use chia_vdf_verify::nucomp::{nucomp, nudupl};
use chia_vdf_verify::primetest::is_prime_bpsw;
use chia_vdf_verify::proof_common::{
    deserialize_form, fast_pow, fast_pow_form_nucomp, get_b, serialize_form,
};
use chia_vdf_verify::reducer::reduce;
/// Integration tests for chia-vdf-verify using real test vectors from chiavdf.
///
/// Test vectors generated by building chiavdf (C++/GMP) and running:
///   seed = "test_seed_chia" (14 bytes)
///   disc_bits = 512
///   x = generator form (a=2, b=1) = the 0x08 BQFC encoding
///   iters = 100
///   y = x^(2^100) with discriminant D
use chia_vdf_verify::verifier::check_proof_of_time_n_wesolowski;
use malachite_base::num::basic::traits::{One, Zero};
use malachite_nz::integer::Integer;

fn hex_decode(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

/// Test vector generated by chiavdf C++ implementation.
/// seed = b"test_seed_chia", disc_bits=512, iters=100
/// x = generator form (BQFC encoding 0x08...)
const ITERS: u64 = 100;
const D_BYTES_HEX: &str = "d0cb181074454b32a0e0fc5e65a1d7625ea43756eaa8de13a9c750c79f7aa60151f065cd5775516159c28713c1e74ced6520f8f5c55129f32f865b28cf7fe8e7";
const X_S_HEX: &str = "08000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const PROOF_BLOB_HEX: &str = "020020417eb39c4e14954a817af644fc13d086c26dddab8afea12415b5e685f7883f5740ba01cb75220081c8aba7854cbd52010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

fn get_discriminant() -> Integer {
    let d_bytes = hex_decode(D_BYTES_HEX);
    -from_bytes_be(&d_bytes)
}

/// Full integration test: verify a real Wesolowski proof from chiavdf.
#[test]
fn test_verify_real_proof_depth0() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS, 0);
    assert!(
        result,
        "check_proof_of_time_n_wesolowski failed on known-good proof"
    );
}

/// Verify that the discriminant we generate matches the test vector.
#[test]
fn test_discriminant_matches_testvector() {
    let seed = b"test_seed_chia";
    let d_rust = create_discriminant(seed, 512);
    let d_expected = get_discriminant();
    assert_eq!(
        d_rust, d_expected,
        "Rust discriminant doesn't match C++ discriminant"
    );
}

/// Verify the discriminant is negative and ≡ 1 (mod 8).
#[test]
fn test_discriminant_properties() {
    let seed = b"test_seed_chia";
    let d = create_discriminant(seed, 512);
    assert!(d < 0i32, "D must be negative");

    let r = fdiv_r(&d, &Integer::from(8i32));
    assert_eq!(r, Integer::from(1i32), "D must be ≡ 1 (mod 8)");

    assert_eq!(num_bits(&d), 512, "D must have exactly 512 bits");

    let p = -d;
    assert!(is_prime_bpsw(&p), "magnitude of D must be prime");
}

/// Verify x (generator form) can be deserialized.
#[test]
fn test_deserialize_generator_form() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s, false).expect("failed to deserialize x");
    assert_eq!(x.a, 2i32, "generator form: a should be 2");
    assert_eq!(x.b, 1i32, "generator form: b should be 1");
}

/// Verify y can be deserialized and has correct discriminant.
#[test]
fn test_deserialize_y_form() {
    let d = get_discriminant();
    let proof_blob = hex_decode(PROOF_BLOB_HEX);
    let y = deserialize_form(&d, &proof_blob[..BQFC_FORM_SIZE], false)
        .expect("failed to deserialize y");

    let disc = &y.b * &y.b - Integer::from(4i32) * &y.a * &y.c;
    assert_eq!(disc, d, "y form has wrong discriminant");
    assert!(y.is_reduced(), "y must be reduced");
}

/// Verify form exponentiation preserves discriminant.
#[test]
fn test_form_exponentiation_preserves_discriminant() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s, false).unwrap();
    let l = Form::compute_l(&d);

    for &exp in &[0u64, 1, 2, 10, 50] {
        let result = fast_pow_form_nucomp(&x, &d, &Integer::from(exp), &l);
        let disc = &result.b * &result.b - Integer::from(4i32) * &result.a * &result.c;
        assert_eq!(
            disc, d,
            "discriminant changed after exponentiation by {exp}"
        );
        assert!(
            result.is_reduced(),
            "form not reduced after exponentiation by {exp}"
        );
    }
}

/// Property: x^0 = identity.
#[test]
fn test_zero_exponentiation_is_identity() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s, false).unwrap();
    let l = Form::compute_l(&d);

    let result = fast_pow_form_nucomp(&x, &d, &Integer::ZERO, &l);
    assert_eq!(result.a, 1i32, "x^0 should be identity (a=1)");
    assert_eq!(result.b, 1i32, "x^0 should be identity (b=1)");
}

/// Property: x^1 = x.
#[test]
fn test_one_exponentiation_is_self() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s, false).unwrap();
    let l = Form::compute_l(&d);

    let result = fast_pow_form_nucomp(&x, &d, &Integer::ONE, &l);
    let mut x_reduced = x.clone();
    reduce(&mut x_reduced);
    assert_eq!(result, x_reduced, "x^1 should equal x");
}

/// Property: nudupl preserves discriminant.
#[test]
fn test_nudupl_discriminant() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s, false).unwrap();
    let l = Form::compute_l(&d);

    let mut f = x;
    for _ in 0..10 {
        f = nudupl(&f, &d, &l);
        reduce(&mut f);
        let disc = &f.b * &f.b - Integer::from(4i32) * &f.a * &f.c;
        assert_eq!(disc, d, "nudupl changed discriminant");
    }
}

/// Property: nucomp is commutative (f*g = g*f after reduction).
#[test]
fn test_nucomp_commutativity() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s, false).unwrap();
    let l = Form::compute_l(&d);

    let y = nudupl(&x, &d, &l);
    let mut y = y;
    reduce(&mut y);

    let mut fg = nucomp(&x, &y, &d, &l);
    reduce(&mut fg);

    let mut gf = nucomp(&y, &x, &d, &l);
    reduce(&mut gf);

    assert_eq!(fg, gf, "nucomp must be commutative");
}

/// Property: reduction is idempotent.
#[test]
fn test_reduction_idempotent() {
    let d = get_discriminant();
    let proof_blob = hex_decode(PROOF_BLOB_HEX);
    let y = deserialize_form(&d, &proof_blob[..BQFC_FORM_SIZE], false).unwrap();

    let mut y2 = y.clone();
    reduce(&mut y2);
    assert_eq!(
        y, y2,
        "reduction should be idempotent on already-reduced form"
    );
}

/// Property: BQFC round-trip for generator and identity forms.
#[test]
fn test_bqfc_roundtrip_special_forms() {
    let d = get_discriminant();
    let d_bits = num_bits(&d);

    let mut identity = Form::identity(&d);
    let bytes = serialize_form(&mut identity, d_bits);
    let f2 = deserialize_form(&d, &bytes, false).unwrap();
    assert_eq!(identity.a, f2.a);
    assert_eq!(identity.b, f2.b);

    let mut generator = Form::generator(&d);
    let bytes = serialize_form(&mut generator, d_bits);
    let f2 = deserialize_form(&d, &bytes, false).unwrap();
    assert_eq!(generator.a, f2.a);
    assert_eq!(generator.b, f2.b);
}

/// Property: BQFC round-trip for the y form from the test vector.
#[test]
fn test_bqfc_roundtrip_y_form() {
    let d = get_discriminant();
    let d_bits = num_bits(&d);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let original_bytes = &proof_blob[..BQFC_FORM_SIZE];
    let y = deserialize_form(&d, original_bytes, false).unwrap();

    let mut y_for_ser = y.clone();
    let re_serialized = serialize_form(&mut y_for_ser, d_bits);
    assert_eq!(
        re_serialized, original_bytes,
        "BQFC serialization of y should match original bytes"
    );
}

/// Verify that GetB matches: B computed from (x, y) matches what's embedded
/// in proof verification (the proof is only valid with the correct B).
#[test]
fn test_get_b_deterministic() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let mut x = deserialize_form(&d, &x_s, false).unwrap();
    let mut y = deserialize_form(&d, &proof_blob[..BQFC_FORM_SIZE], false).unwrap();

    let b1 = get_b(&d, &mut x, &mut y);
    let b2 = get_b(&d, &mut x, &mut y);
    assert_eq!(b1, b2, "GetB must be deterministic");
    assert!(is_prime_bpsw(&b1), "B must be prime");
    assert_eq!(num_bits(&b1), 264, "B must be 264 bits");
}

/// FastPow correctness: 2^100 mod B.
#[test]
fn test_fast_pow_correctness() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let mut x = deserialize_form(&d, &x_s, false).unwrap();
    let mut y = deserialize_form(&d, &proof_blob[..BQFC_FORM_SIZE], false).unwrap();
    let b = get_b(&d, &mut x, &mut y);

    let r = fast_pow(ITERS, &b);
    assert!(r < b, "r must be < B");
    assert!(
        r != Integer::ZERO || ITERS == 0,
        "r should not be 0 for typical cases"
    );
}

// ---------------------------------------------------------------------------
// Mainnet test vector: height=309155, cc_ip, 1024-bit discriminant
//
// Extracted from block height 309155 (challenge-chain infusion-point proof).
// This is the exact case found by differential fuzzing where chiavdf's C++
// BQFC decoder returns True for a mutation that Rust correctly rejects.
//
// Root cause: chiavdf ignores the upper bits of the b0 field (byte 99 of the
// 100-byte y form).  Rust re-serialises the decoded form and checks it matches
// the input byte-for-byte (canonical round-trip), so any change to b0 is
// caught — even bits that chiavdf treats as don't-cares.
// ---------------------------------------------------------------------------

// Big-endian magnitude bytes of the discriminant (negate to get the actual D)
const D_MAINNET_HEX: &str = "d036828612e0ccf69971b6b14438171cf08074bc5ea450b3d5ae0526be867a8015671af4648aa59d64ec06091036385cd351dc5bdf01c694bb915316b4f2fee9509ff1dbaebf6407994962d77aaedd403d08436096cce62465eddcd652f6970ba48e3759f8d226cac0a2976f24de3da40c744286cec5ad666d62a51ac32ac1a7";

// output = y_form (100 bytes) + pi_witness (100 bytes), witness_type = 0
const OUTPUT_MAINNET_HEX: &str = "0300d8262c430e78e7c06cf60c9b2049968f604f3b506a85bfe4fff319f8176760e06cab8ab45524458bf558101f9b4ce8c23cc1e053263272b808b76c6f26493a113b62ded5707b28d9eedc0503ac2efcd32be670726725be0fa7ea01f0ef3f602502010000c3625953c111ba28de77d3e63846cc1063596d44cc8a2cd57a44a60c96b072ba8254485ece15a98b52bdd1907d1359e33929861be12346815a38e083872e5b03c75e2a4d48fdc787f44244f78769c44d186e8446daa45f22e4997f1ded3b96030703";

const ITERS_MAINNET: u64 = 64_670_218;

fn get_mainnet_discriminant() -> Integer {
    let d_bytes = hex_decode(D_MAINNET_HEX);
    -from_bytes_be(&d_bytes)
}

/// Valid mainnet proof verifies correctly.
#[test]
fn test_mainnet_height_309155_valid() {
    let d = get_mainnet_discriminant();
    let x_s = hex_decode(X_S_HEX); // IS_GEN input (0x08 + zeros)
    let output = hex_decode(OUTPUT_MAINNET_HEX);

    assert!(
        check_proof_of_time_n_wesolowski(&d, &x_s, &output, ITERS_MAINNET, 0),
        "mainnet height=309155 cc_ip proof should verify"
    );
}

/// Flipping bits 2+ of the b0 field (y-form byte 99) is rejected by the
/// canonical round-trip check.
///
/// chiavdf 1.1.14 returns True for this mutation — it ignores the upper bits
/// of b0 when reconstructing b, so it recovers the same (a, b) regardless.
/// This test pins the Rust behaviour: we always reject non-canonical b0 values.
#[test]
fn test_mainnet_b0_upper_bits_rejected() {
    let d = get_mainnet_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let output = hex_decode(OUTPUT_MAINNET_HEX);

    // byte 99 = b0 field of y form (g_size=0, 1024-bit disc).
    // Original b0 = 0x01; XOR 0x04 flips bit 2 — upper bits only.
    let mut bad = output.clone();
    bad[99] ^= 0x04;

    assert!(
        !check_proof_of_time_n_wesolowski(&d, &x_s, &bad, ITERS_MAINNET, 0),
        "b0 upper-bit mutation must fail the canonical round-trip check"
    );
}

// Second test vector: seed = "chia-vdf-rust", iters = 200
const ITERS2: u64 = 200;
const D_BYTES2_HEX: &str = "c3ef34d02017540ef26d88057bbfc778da12ed572b99f8707834ed344577c210b1f9287f54a536913177bf5880a4a51b6bfa42445f3fbcd082b695e38c2066d7";
const PROOF_BLOB2_HEX: &str = "030033205ea6d1ab367757073029f1462eb2fcc79749871d0b576f7a392adac84f56f46100e477d59353376f82a3eb56720d010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

/// Second test vector: different seed, 200 iterations.
#[test]
fn test_verify_real_proof_second_vector() {
    let d = {
        let d_bytes = hex_decode(D_BYTES2_HEX);
        -from_bytes_be(&d_bytes)
    };
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB2_HEX);

    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS2, 0);
    assert!(result, "second test vector verification failed");
}

/// Wrong iters should fail verification.
#[test]
fn test_wrong_iters_fails() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS + 1, 0);
    assert!(!result, "wrong iters should fail verification");
}

/// Wrong proof blob size should fail.
#[test]
fn test_wrong_blob_size_fails() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob[..100], ITERS, 0);
    assert!(!result, "truncated blob should fail");

    let mut bad_blob = proof_blob.clone();
    bad_blob.push(0);
    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &bad_blob, ITERS, 0);
    assert!(!result, "extended blob should fail");
}

/// Corrupted y bytes should fail verification.
#[test]
fn test_corrupted_y_fails() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let mut proof_blob = hex_decode(PROOF_BLOB_HEX);

    proof_blob[5] ^= 0x01;
    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS, 0);
    assert!(!result, "corrupted y should fail verification");
}

/// Flipping a padding byte of the y form triggers the BQFC canonical round-trip
/// check and is rejected by the Rust verifier.
///
/// For a 512-bit discriminant the active BQFC region is 52 bytes
/// (2 header + 32 a + 16 t + 1 g + 1 b0); bytes 52–99 must be zero.
/// The Rust deserializer re-serializes the decoded form and checks it matches
/// the input byte-for-byte — any deviation is rejected as non-canonical.
///
/// chiavdf's C++ decoder does not perform this round-trip check and ignores
/// bytes beyond the active region.  This is the discrepancy found by
/// differential fuzzing (scripts/differential_fuzz.py).
#[test]
fn test_non_canonical_y_padding_rejected() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let mut proof_blob = hex_decode(PROOF_BLOB_HEX);

    // Byte 52 is the first zero-padding byte of the y form.
    proof_blob[52] ^= 0x01;
    assert!(
        !check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS, 0),
        "non-zero y-form padding should fail the canonical round-trip check"
    );
}

/// IS_1 and IS_GEN forms use only byte 0; bytes 1–99 are don't-cares and are
/// silently ignored by the deserializer (early return before canonical check).
///
/// In this test vector the pi (witness) form is the identity (IS_1, byte 0 =
/// 0x04), so any mutation to its trailing bytes still decodes to (a=1, b=1)
/// and verification passes unchanged.  The same applies to x (IS_GEN, 0x08).
///
/// This is the complementary case to test_non_canonical_y_padding_rejected:
/// the canonical check only fires for ordinary (non-special) forms.
#[test]
fn test_is1_isgen_trailing_bytes_ignored() {
    let d = get_discriminant();
    let mut x_s = hex_decode(X_S_HEX); // IS_GEN (0x08): bytes 1-99 ignored
    let mut proof_blob = hex_decode(PROOF_BLOB_HEX); // pi form is IS_1 (0x04): bytes 101-199 ignored

    x_s[99] ^= 0xff;
    proof_blob[199] ^= 0xff; // last byte of IS_1 pi form
    assert!(
        check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS, 0),
        "trailing bytes of IS_GEN/IS_1 forms are don't-cares; proof should still verify"
    );
}

/// Corrupted proof bytes should fail verification.
#[test]
fn test_corrupted_proof_fails() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let mut proof_blob = hex_decode(PROOF_BLOB_HEX);

    proof_blob[BQFC_FORM_SIZE] = 0x00;
    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS, 0);
    assert!(!result, "corrupted proof should fail verification");
}

// ---------------------------------------------------------------------------
// vdf.txt stress-test vectors from chiavdf (1024-bit discriminant, depth 0..7)
// ---------------------------------------------------------------------------

const VDF_TXT: &str = include_str!("fixtures/vdf.txt");

struct VdfVec<'a> {
    challenge: &'a str,
    disc_bits: usize,
    input: &'a str,
    proof: &'a str,
    iters: u64,
    depth: u64,
}

fn parse_vdf_txt(content: &str) -> Vec<VdfVec<'_>> {
    let lines: Vec<&str> = content.lines().filter(|l| !l.is_empty()).collect();
    let mut out = Vec::new();
    for chunk in lines.chunks(6) {
        if chunk.len() < 6 {
            continue;
        }
        out.push(VdfVec {
            challenge: chunk[0],
            disc_bits: chunk[1].parse().unwrap(),
            input: chunk[2],
            proof: chunk[3],
            iters: chunk[4].parse().unwrap(),
            depth: chunk[5].parse().unwrap(),
        });
    }
    out
}

fn verify_vdf_vec(v: &VdfVec<'_>) -> bool {
    let challenge = hex_decode(v.challenge);
    let d = create_discriminant(&challenge, v.disc_bits);
    let input = hex_decode(v.input);
    let proof = hex_decode(v.proof);
    check_proof_of_time_n_wesolowski(&d, &input, &proof, v.iters, v.depth)
}

/// Fast smoke test: one depth=0 and one depth=2 vector from vdf.txt.
/// Exercises the 1024-bit discriminant path in ~35 ms (release) per vector.
#[test]
fn test_vdf_txt_sample() {
    let vecs = parse_vdf_txt(VDF_TXT);

    let d0 = vecs.iter().find(|v| v.depth == 0).expect("depth=0 vector");
    assert!(verify_vdf_vec(d0), "depth=0 vector failed");

    let d2 = vecs.iter().find(|v| v.depth == 2).expect("depth=2 vector");
    assert!(verify_vdf_vec(d2), "depth=2 vector failed");
}

/// Full vdf.txt test suite — all 110 vectors (depth 0..7, 1024-bit discriminant).
/// Skipped by default due to runtime (~15 s release / ~70 s debug).
/// Run with: cargo test --release -- --ignored test_vdf_txt_all
#[test]
#[ignore = "slow: ~15s release / ~70s debug"]
fn test_vdf_txt_all() {
    let vecs = parse_vdf_txt(VDF_TXT);
    let mut passed = 0;
    let mut failed = 0;

    for v in &vecs {
        if verify_vdf_vec(v) {
            passed += 1;
        } else {
            failed += 1;
            eprintln!(
                "FAIL depth={} iters={} challenge={}...",
                v.depth,
                v.iters,
                &v.challenge[..12]
            );
        }
    }

    assert_eq!(failed, 0, "{}/{} vectors failed", failed, passed + failed);
}
