[build-system]
requires = ["maturin~=1.7"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
features = ["pyo3/extension-module"]
python-source = "python"

[project]
name = "chia_rs"
dependencies = ["typing_extensions"]
